hash-format = "sha256"

[[files]]
file = "config/fabric_loader_dependencies.json"
hash = "0443df9f50bba53b3dc8ec6b055aa120c03d2016cc6bd8b2358d018feaca13e3"

[[files]]
file = "config/isxander-main-menu-credits.json"
hash = "63922c610a44a647d054f25ffbf729b7698a970215d26f0ee16944056d8414f1"

[[files]]
file = "config/yosbr/yosbr/config/audioplayer/audioplayer-server.properties"
hash = "1e611c9173c793c6434b998bcaaf40b0f3a0131ab3619292c1a4384594db4121"

[[files]]
file = "config/yosbr/yosbr/config/iris.properties"
hash = "2b9348b31a8a0d8239c5a3bf9cc3afb7b6d2a7b1bc14cd3558bb2c6c72bc7028"

[[files]]
file = "config/yosbr/yosbr/config/voicechat/translations.properties"
hash = "b8215b84232be41438ffb7c7304b57b0677c9cad49b717db59900872080adf20"

[[files]]
file = "config/yosbr/yosbr/config/voicechat/username-cache.json"
hash = "080e092a2cdf65562653c853debb74b8a052c9423a12598eada8076de8ef9648"

[[files]]
file = "config/yosbr/yosbr/config/voicechat/voicechat-client.properties"
hash = "90fe49918c922fc32f98ccf770ca16651da6d2c02d042578e708397c5be15ba5"

[[files]]
file = "config/yosbr/yosbr/config/voicechat/voicechat-server.properties"
hash = "7d49f4a92ed5c5490880869e52a58d291f787f42d93923697aa388830cab3e62"

[[files]]
file = "config/yosbr/yosbr/config/voicechat/voicechat-volumes.properties"
hash = "58242ef3075b166845e0081281b01113a55b9d095104a68b167e7b4bc08b87c5"

[[files]]
file = "config/yosbr/yosbr/options.txt"
hash = "60a70f784e3eb1c0789be2211975dfbeef4dc08641b554855db0b3c364f43c12"

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6187b9cadca608c7d1a00c9fe3a826a2dbfa20f089235147fc9bcfdd85f0c250"
metafile = true

[[files]]
file = "mods/audioplayer.pw.toml"
hash = "bc4ce5c913b803da7e696c527332f4862092e747d815595b3afc9eae330f03ba"
metafile = true

[[files]]
file = "mods/better-clouds.pw.toml"
hash = "d2933afa6dcca20f4846bc1977fecc4ed759dc7af53896274dd133242d22693e"
metafile = true

[[files]]
file = "mods/better-stats.pw.toml"
hash = "176416942af86d1b6ee0dc826806680eb48f05348cc0897e37fdec5f988306c0"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "59658f3b9d3b86b24440008fd2031c53d538cbb35e84524bcdbc67f0de7ea251"
metafile = true

[[files]]
file = "mods/bettergrassify.pw.toml"
hash = "d74546a98e3af1867539d80bdf9d188968920a7df8e57ccb3b7a55b36a37eb7a"
metafile = true

[[files]]
file = "mods/boat-item-view.pw.toml"
hash = "6d717e11f5a11194004d8879b5c1e46448394855211ce8ac1937ae40895f2c27"
metafile = true

[[files]]
file = "mods/capes.pw.toml"
hash = "e02c60e3243dde712fcdc279f0ee21d31f530d58f11402c0fcb082bb429e339d"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "4a9910d74bb7a85600abaf36ae568bcfb10e76062b9d5d718656f5d172e79419"
metafile = true

[[files]]
file = "mods/chatanimation.pw.toml"
hash = "783d509d7069d90ca34641f64936fc0eba7b974f0209e40a7ce915e4436e3309"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a90139b002d632ba9256cb3e7e877945bf8e3afa5b191d1adc83c5e3eb72da4c"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "63fe49aaee4880ff28e30aa558084f7322d5ec2bf110022bc5ae89a9be5cf2bf"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "2c31d52ada2aec45150617516523aaae57f30df0f8bb1ef1115e1825e5a89759"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5443c56a46d7fca84a1f96dc58315951a24cf8954f059aa35f213f28214d468d"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "2a9e9968c598e234a84ccd9afc80a424d5c2ad9a37e4c85a0d36d06ddc9ebfa9"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "48a71da0cd96100ccc239fa88fb6280094f0a0b1a555a2bdcc2e58dc2d7ebcc5"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "186a261ded1911abf559dce21b22eadc1e96de7767982e58f458b82a89a924ba"
metafile = true

[[files]]
file = "mods/held-item-info.pw.toml"
hash = "15bce919514325447e487d260ec4458165fb4537ccadb9a0e740df4bcf3cb0ef"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "5a6ee9ae2de75743aa027eb753ac9c3cb92305df67bde8fe2cefdd2df0eb49d7"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "4ed061d122cb39f34ed730984c7bcf03437250f24a21975203bb4598d7d86a14"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "a077e0482f50add9ef20e962a7939aa678583cb3f354fb6b6124219badafdd4d"
metafile = true

[[files]]
file = "mods/lambdynamiclights.pw.toml"
hash = "55c7b1073141a49fbd6d3ba480bd95049f7978513e8261ec2bedab8e82409836"
metafile = true

[[files]]
file = "mods/libjf.pw.toml"
hash = "eea065fad43e5517689fdd4a5c21f90209b6cfe7f0708dcbeca63c772aa17cc7"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "7fc67cabd5de89ebe9d7d995cdf160ceff0572c2bef784e846675976a428c9fa"
metafile = true

[[files]]
file = "mods/main-menu-credits.pw.toml"
hash = "fa3e6df3d222c94014c840673aa92455210d404eadceb05dd5ab3ae5a3eab6db"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "5dd45d5fd5e1ae2bd521b93a70b83c69b57ada18f424c6562d8c6ea9980cfb3e"
metafile = true

[[files]]
file = "mods/morechathistory.pw.toml"
hash = "096bce1d87ff7f759d07ae6501043c5d2db1bcdffb5ea566425843f12ff8e348"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "204a4b3b041fad4bb4dc543c74d540fcf239710494d2130cebe700bf1d8a7805"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "dc24a4cc0ad484d6593997c197ea602fac4d98c45dab0de6421e704c3851acd9"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "70d7b2bca719eca2b3a1447228b868abdc633c38121652d49f4e34380c44339d"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "958d770c8024a7c901315c786f6060554b5583ae302068526766e42c31b5f604"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
hash = "4bf3b4e6ce176f34d70fa961fee580956567b0a79e25e3be58e020b7e9f42e32"
metafile = true

[[files]]
file = "mods/paginatedadvancements.pw.toml"
hash = "6191573c029c9c55c1b813c9c2d0fa777597630cd74b62e7486841b792d95d68"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "e674752dd4dd07c33d9b94f6e19c15ef893c356c3c5ed77aeaf35cf6d2325130"
metafile = true

[[files]]
file = "mods/puzzle.pw.toml"
hash = "978c05608ae60f7e40925d145910c124bb90db5db0ea8f8786fccd677eced4d6"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "1600b1e64b297d68bafb4f5e5eeef08117645ac24922696da10c711ae587c06b"
metafile = true

[[files]]
file = "mods/respackopts.pw.toml"
hash = "1ad051378a03a9db2bfd91751a1439b41c30b8a7637242b3a259150c60421dde"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "bd7760e94351d6e7c19eb1f155c7a5a7fd281340b7bd556da2765e931f6c9ab5"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "85ebe0d8d1f0f6bd943c1a87f5df47869fde7ede4d9d0bc90a2aff13a760c5dc"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "4f57108f9e1c6281cfdaf3812e6bc2a2f16609a845c9912218ada90b1603e1b3"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "e8c961dbadf2dde334c857d0b42a6c6452aa77a146cf80d4febf7f46e4ac2ef6"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "ae52c6ae8a2f2e6ab55d9387e0fa25447f62866fed9acc5758acfb8b1907eabf"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2520b331c2b0eb582b448c4ebf1a73d66d42184acc2d74912baef4140e05ee9b"
metafile = true

[[files]]
file = "mods/tcdcommons.pw.toml"
hash = "a238e01cf0ab13c06e281717fb73e01e9d106c01b0ae55a6fbf893333976c9e1"
metafile = true

[[files]]
file = "mods/visuality.pw.toml"
hash = "61d853a4f2d353ac126a8196414efc82d0ca0402da2a8e492383dd539bfe4976"
metafile = true

[[files]]
file = "mods/world-play-time.pw.toml"
hash = "aa0c01cae50141e33d840f4d98b1492300a16bc623df7421e224447dcf098fb8"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "cfa4ddfc8999e7be331c6dad1f2a0372f996243241d21697939e6838b3402c6d"
metafile = true

[[files]]
file = "mods/yosbr.pw.toml"
hash = "1bb9b2e75c6934b1f18648e9b37e20abcf6a4a2547c7cdb0abe88407267e0c10"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "22052f42b1b73226d9508ef42af962471c79c7daa281aac66a82a90c7d7bb9e5"
metafile = true

[[files]]
file = "resourcepacks/Redstone Tweaks 2.5.2.zip.rpo"
hash = "5c353417428ccd7e9182d2a4ff226640dcea2af2d90b9a0876219545be60577c"

[[files]]
file = "resourcepacks/redstone-tweaks.pw.toml"
hash = "d36d0104f40c65ec6e8f7b37c33662ebe57f06e1c3864f9458fd4ea534f4af6a"
metafile = true
