name = "CoreOptimized"
author = "SniperXJohn"
version = "1.6.0-alpha.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a10876b06faaa527095968ab8056808909b37ce89c6432af81ef85ed2aee7fbb"

[versions]
fabric = "0.17.3"
minecraft = "1.21.9"
