name = "CoreOptimized"
author = "SniperXJohn"
version = "1.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ada36af7c4adb68299f159ea0ec56f1b34fb29c223286b73f3c391f3cc907b4"

[versions]
fabric = "0.17.3"
minecraft = "1.21.8"
